//! Owner feature 22: the generated `anti-hall:engine` skill family cannot go stale or bloat, and the role matrix is enforced.
//! The skills are compared with the committed files (regenerate with `scripts/gen-engine-skills.sh`), each is held to its size
//! budget, every implemented verb has a matrix row, each role's allowed and refused verbs are checked on the command line and in
//! the PreToolUse guard, the role is detected for every kind of caller, and the injected note is capped and per role.
#![allow(clippy::unwrap_used, clippy::expect_used)] // a test crate: a panic is the failure report, and E2 exempts tests

use ah_engine::reqenv::RequestEnv;
use ah_engine::{roles, skillgen};
use serde_json::{Value, json};
use std::io::Write;
use std::path::PathBuf;
use std::process::{Command, Stdio};

fn plugin() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../plugins/anti-hall")
}

fn args(a: &[&str]) -> Vec<String> {
    a.iter().map(|s| s.to_string()).collect()
}

#[test]
fn the_committed_skills_equal_the_generated_ones_for_both_hosts() {
    assert_eq!(skillgen::hosts().len(), 2, "Claude and Codex");
    for host in skillgen::hosts() {
        for s in skillgen::family(host) {
            let committed = std::fs::read_to_string(plugin().join(&s.path)).unwrap_or_default();
            assert!(
                committed == s.text,
                "{} is stale: run ah-engine/scripts/gen-engine-skills.sh and commit ({} bytes committed, {} generated)",
                s.path,
                committed.len(),
                s.text.len()
            );
        }
    }
}

#[test]
fn no_committed_engine_skill_is_outside_the_generated_family() {
    for host in skillgen::hosts() {
        let family = skillgen::family(host);
        let (dir, prefix) = if host == "codex" { ("codex/skills", "anti-hall-engine") } else { ("skills", "engine") };
        for e in std::fs::read_dir(plugin().join(dir)).unwrap().flatten() {
            let n = e.file_name().to_string_lossy().to_string();
            if n.starts_with(prefix) {
                assert!(
                    family.iter().any(|s| s.path == format!("{dir}/{n}/SKILL.md")),
                    "{dir}/{n} is not generated by the registry (an area was emptied or renamed)"
                );
            }
        }
    }
}

#[test]
fn every_skill_is_within_its_size_budget_and_the_main_one_is_tiny() {
    for host in skillgen::hosts() {
        for s in skillgen::family(host) {
            assert!(
                s.text.len() <= skillgen::budget(&s),
                "{} is {} bytes, over its {} byte budget (roles.skill_budget): split the area",
                s.path,
                s.text.len(),
                skillgen::budget(&s)
            );
        }
    }
    let main = skillgen::family("claude").remove(0);
    assert!(main.main && main.text.len() < 4000);
}

#[test]
fn every_skill_has_a_use_when_description_and_the_main_one_points_at_every_area() {
    for host in skillgen::hosts() {
        let fam = skillgen::family(host);
        for s in &fam {
            let d = s.text.lines().find(|l| l.starts_with("description: ")).unwrap();
            assert!(d.starts_with("description: \"Use when "), "{}: {d}", s.path);
            assert!(s.text.lines().nth(1).unwrap().starts_with("name: "));
        }
        for s in fam.iter().filter(|s| !s.main) {
            assert!(fam[0].text.contains(&format!("`{}`", skillgen_ref(host, &s.name))), "the main skill does not point at {}", s.name);
        }
    }
}

fn skillgen_ref(host: &str, name: &str) -> String {
    let bare = name.trim_start_matches("anti-hall-");
    if host == "codex" { format!("$anti-hall-{bare}") } else { format!("/anti-hall:{bare}") }
}

#[test]
fn the_codex_family_has_the_same_areas_and_the_same_verbs_as_the_claude_one() {
    let strip = |name: &str| name.trim_start_matches("anti-hall-").to_string();
    let a: Vec<String> = skillgen::family("claude").iter().map(|s| strip(&s.name)).collect();
    let b: Vec<String> = skillgen::family("codex").iter().map(|s| strip(&s.name)).collect();
    assert_eq!(a, b);
    let verbs = |host: &str| -> Vec<String> {
        skillgen::family(host)
            .iter()
            .flat_map(|s| {
                s.text.lines().filter(|l| l.starts_with("| `ah-engine ")).map(|l| l.split('|').nth(1).unwrap().trim().to_string()).collect::<Vec<_>>()
            })
            .collect()
    };
    assert_eq!(verbs("claude"), verbs("codex"));
}

#[test]
fn every_implemented_verb_has_a_matrix_row_in_a_known_area_and_no_row_is_orphaned() {
    let implemented: Vec<String> = ah_engine::cli::commands().into_iter().filter(|c| c.status == "implemented").map(|c| c.name).collect();
    for v in &implemented {
        let r = roles::row(v).unwrap_or_else(|| panic!("verb {v} has no roles.matrix row: declare which roles may use it"));
        assert!(!r.roles.is_empty(), "{v}");
        for x in r.roles.iter().chain(&r.self_only) {
            assert!(roles::names().contains(x), "{v}: unknown role {x}");
        }
    }
    for v in roles::verbs() {
        assert!(implemented.iter().any(|i| i == v), "roles.matrix names {v}, which is not an implemented command");
    }
    for c in ah_engine::checks::registry() {
        assert!(!skillgen::check_area(c.name()).is_empty());
    }
}

#[test]
fn the_default_matrix_keeps_owner_level_verbs_for_the_main_session() {
    for v in ["restore", "stop", "ctl", "serve", "reset", "maintain", "backup", "migrate", "jev-setup", "jev_sweep"] {
        let r = roles::row(v).unwrap();
        assert!(!r.roles.contains(&"subagent") && !r.roles.contains(&"workspace"), "{v} must not be open to subagents or workspace children");
    }
    for v in ["version", "status", "metrics", "impact", "docs", "check"] {
        assert!(roles::row(v).unwrap().roles.contains(&"subagent"), "{v} is a read verb every role may use");
    }
    let mesh = roles::row("mesh").unwrap();
    assert_eq!(mesh.self_only, vec!["workspace"]);
}

fn env(pairs: &[(&str, &str)]) -> RequestEnv {
    RequestEnv::from_pairs(pairs.iter().copied())
}

#[test]
fn the_command_line_role_comes_from_the_environment_and_a_declaration_only_narrows() {
    assert_eq!(roles::role_from_env(&env(&[("HOME", "/h")])), "main");
    assert_eq!(roles::role_from_env(&env(&[("HOME", "/h"), ("DEVSWARM_SOURCE_BRANCH", "feat/x")])), "workspace");
    assert_eq!(roles::role_from_env(&env(&[("HOME", "/h"), ("DEVSWARM_SOURCE_BRANCH", "")])), "main", "a Primary has an empty branch");
    assert_eq!(roles::role_from_env(&env(&[("HOME", "/h"), ("ANTIHALL_ROLE", "subagent")])), "subagent");
    assert_eq!(roles::role_from_env(&env(&[("HOME", "/h"), ("ANTIHALL_ROLE", "codex")])), "codex");
    assert_eq!(
        roles::role_from_env(&env(&[("HOME", "/h"), ("DEVSWARM_SOURCE_BRANCH", "b"), ("ANTIHALL_ROLE", "main")])),
        "workspace",
        "a declaration never widens"
    );
    assert_eq!(roles::role_from_env(&env(&[("HOME", "/h"), ("ANTIHALL_ROLE", "nonsense")])), "main");
}

#[test]
fn each_role_runs_what_the_matrix_allows_and_is_refused_the_rest_with_who_may() {
    let e = env(&[("HOME", "/h"), ("DEVSWARM_BUILDER_ID", "ws-1")]);
    // main and the Codex main seat run owner-level verbs
    for role in ["main", "codex"] {
        for v in ["restore", "stop", "jev-setup", "mesh", "status"] {
            assert!(roles::check(role, v, &[], &e).is_ok(), "{role} {v}");
        }
    }
    // a subagent: read verbs yes, owner-level no, owner args no
    assert!(roles::check("subagent", "status", &[], &e).is_ok());
    assert!(roles::check("subagent", "doctor", &args(&["--check"]), &e).is_ok());
    let m = roles::check("subagent", "restore", &args(&["snap"]), &e).unwrap_err();
    assert!(m.contains("`restore`") && m.contains("subagent") && m.contains("main") && m.contains("codex"), "{m}");
    let m = roles::check("subagent", "doctor", &args(&["--repair"]), &e).unwrap_err();
    assert!(m.contains("reserved for the main session"), "{m}");
    assert!(roles::check("main", "doctor", &args(&["--repair"]), &e).is_ok());
    assert!(roles::check("subagent", "proj", &args(&["/x", "put"]), &e).is_err(), "a subagent has no project mailbox");
    // a workspace child: itself only
    assert!(roles::check("workspace", "mesh", &args(&["read", "--id", "ws-1"]), &e).is_ok());
    let m = roles::check("workspace", "mesh", &args(&["read", "--id", "ws-2"]), &e).unwrap_err();
    assert!(m.contains("ws-2") && m.contains("ws-1"), "{m}");
    assert!(roles::check("workspace", "mesh", &args(&["roster"]), &e).is_ok());
    assert!(roles::check("workspace", "stop", &[], &e).is_err());
    assert!(roles::check("workspace", "config", &args(&["heal"]), &e).is_err());
    assert!(roles::check("workspace", "config", &[], &e).is_ok());
    // a verb the matrix does not know is not this module's to judge
    assert!(roles::check("subagent", "no-such-verb", &[], &e).is_ok());
}

/// Run the built binary with a clean environment.
fn run(argv: &[&str], extra: &[(&str, &str)], stdin: &str) -> (i32, String, String) {
    let dir = PathBuf::from(env!("CARGO_TARGET_TMPDIR")).join(format!("roles-{}", std::process::id()));
    std::fs::create_dir_all(dir.join("home")).unwrap();
    let mut c = Command::new(env!("CARGO_BIN_EXE_ah-engine"));
    c.args(argv)
        .env_clear()
        .env("PATH", std::env::var("PATH").unwrap_or_default())
        .env("HOME", dir.join("home"))
        .env("AH_ENGINE_DIR", dir.join("state"))
        .env("AH_ENGINE_NOSPAWN", "1")
        .env("AH_ENGINE_PLUGIN_ROOT", plugin())
        .current_dir(&dir)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());
    c.envs(extra.iter().copied());
    let mut ch = c.spawn().unwrap();
    ch.stdin.take().unwrap().write_all(stdin.as_bytes()).unwrap();
    let o = ch.wait_with_output().unwrap();
    (o.status.code().unwrap_or(-1), String::from_utf8_lossy(&o.stdout).to_string(), String::from_utf8_lossy(&o.stderr).to_string())
}

#[test]
fn the_command_line_refuses_a_workspace_child_an_owner_verb_and_a_sibling() {
    let ws = [("DEVSWARM_SOURCE_BRANCH", "feat/x"), ("DEVSWARM_BUILDER_ID", "ws-1")];
    let (code, _, err) = run(&["restore", "nowhere"], &ws, "");
    assert_eq!(code, 77, "{err}");
    assert!(err.contains("not available to workspace sessions") && err.contains("main"), "{err}");
    let (code, out, _) = run(&["--json", "stop"], &ws, "");
    assert_eq!(code, 77);
    assert!(out.contains("\"error\""), "{out}");
    let (code, _, err) = run(&["mesh", "read", "--db", "/nonexistent/x.db", "--id", "ws-2"], &ws, "");
    assert_eq!(code, 77, "{err}");
    assert!(err.contains("may only act on itself"), "{err}");
    // a read verb is open to it, and the main session is not gated
    assert_eq!(run(&["version"], &ws, "").0, 0);
    assert_eq!(run(&["version"], &[], "").0, 0);
    // the switch: off lets the child run it (the verb itself then fails on its own terms, not with the role exit)
    let off = [("DEVSWARM_SOURCE_BRANCH", "feat/x"), ("ANTIHALL_ROLE_GUARD", "0")];
    assert_ne!(run(&["restore", "nowhere"], &off, "").0, 77);
}

fn payload(event: &str, extra: Value) -> String {
    let mut p = json!({"session_id": "s1", "cwd": "/tmp", "hook_event_name": event});
    for (k, v) in extra.as_object().unwrap() {
        p[k] = v.clone();
    }
    p.to_string()
}

fn note(extra: Value, env_pairs: &[(&str, &str)], event: &str) -> String {
    let (code, out, err) = run(&["check", "engine-role-note"], env_pairs, &payload(event, extra));
    assert_eq!(code, 0, "{err}");
    let v: Value = serde_json::from_str(out.trim()).unwrap_or_else(|_| panic!("no note: {out:?} {err}"));
    v["hookSpecificOutput"]["additionalContext"].as_str().unwrap().to_string()
}

#[test]
fn the_role_note_names_the_role_lists_only_what_it_may_use_and_points_at_the_main_skill() {
    let main = note(json!({}), &[], "SessionStart");
    let ws = note(json!({}), &[("DEVSWARM_SOURCE_BRANCH", "b")], "SessionStart");
    let sub = note(json!({"agent_id": "a1", "agent_type": "general-purpose"}), &[], "SubagentStart");
    let codex = note(json!({"turn_id": "t1", "model": "gpt"}), &[], "SessionStart");
    for (n, role) in [(&main, "main"), (&ws, "workspace"), (&sub, "subagent"), (&codex, "codex")] {
        assert!(n.contains(&format!("(role: {role})")), "{role}: {n}");
        assert!(n.chars().count() <= ah_engine::defaults::num("roles.note_max") as usize, "{role}: {} chars", n.chars().count());
        assert!(n.len() < 10_000, "inside the hook injection cap");
    }
    assert!(main.contains("restore") && main.contains("jev-setup"));
    assert!(!sub.contains("restore") && !sub.contains("proj") && sub.contains("status"), "{sub}");
    assert!(!ws.contains("restore") && ws.contains("proj") && ws.contains("mesh"), "{ws}");
    assert!(main.contains("/anti-hall:engine") && !main.contains("engine-"), "points at the main skill only: {main}");
    assert!(sub.contains("/anti-hall:engine"));
    assert!(codex.contains("$anti-hall-engine") && !codex.contains("/anti-hall:"), "{codex}");
}

#[test]
fn the_role_note_switch_and_the_cap_are_settings() {
    let (code, out, _) = run(&["check", "engine-role-note"], &[("ANTIHALL_ROLE_NOTE", "0")], &payload("SessionStart", json!({})));
    assert_eq!(code, 0);
    assert!(out.trim().is_empty(), "off means silence: {out}");
}

fn guard(cmd: &str, extra: Value, env_pairs: &[(&str, &str)]) -> (i32, String) {
    let mut p: Value = serde_json::from_str(&payload("PreToolUse", json!({"tool_name": "Bash"}))).unwrap();
    p["tool_input"] = json!({"command": cmd});
    for (k, v) in extra.as_object().unwrap() {
        p[k] = v.clone();
    }
    let (code, out, err) = run(&["check", "engine-role-guard"], env_pairs, &p.to_string());
    (code, format!("{out}{err}"))
}

#[test]
fn the_pretooluse_guard_refuses_what_a_subagent_or_a_workspace_child_may_not_run() {
    let sub = json!({"agent_id": "a1", "agent_type": "general-purpose"});
    let (code, err) = guard("ah-engine restore snap", sub.clone(), &[]);
    assert_eq!(code, 2, "{err}");
    assert!(err.contains("not available to subagent sessions") || err.contains("restore"), "{err}");
    assert_eq!(guard("ah-engine status --json", sub.clone(), &[]).0, 0);
    assert_eq!(guard("cd x && ~/.anti-hall/ah-engine/bin/ah-engine stop; ls", sub.clone(), &[]).0, 2, "a path-qualified binary, after a shell operator");
    assert_eq!(guard("ls | ah-engine --json status", sub.clone(), &[]).0, 0, "a leading flag is skipped");
    assert_eq!(guard("echo ah-engine-notes restore", sub, &[]).0, 0, "the word inside another name is not a call");
    // the main session may; a workspace child may not, and may not name a sibling
    assert_eq!(guard("ah-engine restore snap", json!({}), &[]).0, 0);
    let ws = [("DEVSWARM_SOURCE_BRANCH", "b"), ("DEVSWARM_BUILDER_ID", "ws-1")];
    assert_eq!(guard("ah-engine restore snap", json!({}), &ws).0, 2);
    assert_eq!(guard("ah-engine mesh read --db x --id ws-1", json!({}), &ws).0, 0);
    let (code, err) = guard("ah-engine mesh read --db x --id ws-2", json!({}), &ws);
    assert_eq!(code, 2);
    assert!(err.contains("ws-2"), "{err}");
    // no engine call, no work
    assert_eq!(guard("git status", json!({"agent_id": "a1"}), &[]).0, 0);
    // switch off
    assert_eq!(guard("ah-engine restore snap", json!({"agent_id": "a1"}), &[("ANTIHALL_ROLE_GUARD", "0")]).0, 0);
}

#[test]
fn the_codex_guard_sees_a_codex_subagent_as_a_subagent() {
    let cx = json!({"turn_id": "t1", "model": "gpt", "agent_id": "a1", "agent_type": "worker"});
    assert_eq!(guard("ah-engine restore snap", cx, &[]).0, 2);
    assert_eq!(guard("ah-engine restore snap", json!({"turn_id": "t1", "model": "gpt"}), &[]).0, 0, "a Codex top-level session is the main seat");
}

#[test]
fn the_role_checks_are_in_the_dispatch_table_for_both_hosts() {
    use ah_engine::dispatch::table;
    let has = |host: &str, event: &str, id: &str| table::entries(host, event).iter().any(|e| e.id == id);
    assert!(
        has("claude", "SessionStart", "engine-role-note")
            && has("claude", "SubagentStart", "engine-role-note")
            && has("claude", "PreToolUse", "engine-role-guard")
    );
    assert!(has("codex", "SessionStart", "engine-role-note") && has("codex", "PreToolUse", "engine-role-guard"));
}
