'use strict';
// PROTOCOL.md (cost-trim Phase 3, test class 1: doctrine coverage). The file is generated by
// tools/gen-protocol.js from the arrays verify-first-core.js owns; every line any hook sends under
// context.protocolLevel=full (today's text, the pins verify-first-{full,orch,subagent}.test.js hold)
// must be inside it: no needle is deleted, only moved.

const { test } = require('node:test');
const assert = require('node:assert');
const { spawnSync } = require('node:child_process');
const T = require('../helpers/cost-trim.js');
const { fs, path, CORE } = T;
const { testHook } = require('../helpers/spawn-hook.js');

const REPO = path.join(__dirname, '..', '..');
const FULL = { ANTIHALL_PROTOCOL_LEVEL: 'full' };
const md = fs.readFileSync(CORE.PROTOCOL_PATH, 'utf8');

test('node tools/gen-protocol.js --check: PROTOCOL.md is not stale', () => {
  const r = spawnSync(process.execPath, [path.join(REPO, 'tools', 'gen-protocol.js'), '--check'], { encoding: 'utf8' });
  assert.strictEqual(r.status, 0, r.stderr);
});

test('--check fails on a stale or missing file and passes on a fresh one', () => {
  const dir = fs.mkdtempSync(path.join(require('node:os').tmpdir(), 'gen-protocol-'));
  try {
    const f = path.join(dir, 'PROTOCOL.md');
    const gen = (...a) => spawnSync(process.execPath, [path.join(REPO, 'tools', 'gen-protocol.js'), ...a, '--out', f], { encoding: 'utf8' });
    assert.strictEqual(gen('--check').status, 1, 'missing');
    assert.strictEqual(gen().status, 0);
    assert.strictEqual(gen('--check').status, 0, 'fresh');
    fs.appendFileSync(f, 'drift\n');
    assert.strictEqual(gen('--check').status, 1, 'stale');
    assert.strictEqual(fs.readFileSync(f, 'utf8').endsWith('drift\n'), true, '--check never rewrites');
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
});

function linesOf(text) { return String(text).split('\n').filter((l) => l.trim()); }

test('every line of every full-level hook output is in PROTOCOL.md', () => {
  const h = T.claudeHome();
  try {
    const sess = { hook_event_name: 'SessionStart', source: 'startup', session_id: 't', cwd: h.home };
    const sub = { hook_event_name: 'SubagentStart', session_id: 't', agent_id: 'a1', agent_type: 'general-purpose', cwd: h.home };
    const outs = {
      core: T.ctxOf(testHook('verify-first-full.js', sess, { home: h.home, env: FULL, expectJson: true })),
      orch: T.ctxOf(testHook('verify-first-orch.js', sess, { home: h.home, env: FULL, expectJson: true })),
      primary: T.ctxOf(testHook('verify-first-orch.js', sess, { home: h.home, env: { ...FULL, DEVSWARM_REPO_ID: 'repo-x' }, expectJson: true })),
      sub: T.ctxOf(testHook('verify-first-subagent.js', sub, { home: h.home, env: FULL, expectJson: true })),
      child: T.ctxOf(testHook('verify-first-subagent.js', sub, { home: h.home, env: { ...FULL, DEVSWARM_REPO_ID: 'repo-x', DEVSWARM_SOURCE_BRANCH: 'f/x' }, expectJson: true })),
    };
    for (const [name, text] of Object.entries(outs)) {
      assert.ok(text.length > 1000, name + ' produced text');
      const missing = linesOf(text).filter((l) => !md.includes(l));
      // The child-workspace note is the one line PROTOCOL.md carries with a lead-in label.
      assert.deepStrictEqual(missing.filter((l) => !/^You are a subagent inside a DevSwarm child workspace/.test(l)), [], name + ' lines missing from PROTOCOL.md');
    }
    assert.ok(md.includes(CORE.CHILD_WORKSPACE_MAILBOX_NOTE));
  } finally { h.cleanup(); }
});

test('PROTOCOL.md keeps rules A-N in order, the W spawn command, and the #orchestration anchor target', () => {
  const orch = md.slice(md.indexOf('## Orchestration'));
  const letters = [...orch.matchAll(/^ {2}([A-N])\. /gm)].map((m) => m[1]);
  assert.deepStrictEqual(letters, 'ABCDEFGHIJKLMN'.split(''));
  assert.ok(md.includes('node scripts/devswarm.js spawn <branch> -p "<brief>"'));
  assert.ok(/^## Orchestration$/m.test(md), 'heading anchors as #orchestration');
});

test('every compact letter/clause has its full-rule home in PROTOCOL.md (compact text is a subset in meaning)', () => {
  // The compact orchestration names letters A/E, B, L, G, M/N, K; each must exist as a full rule.
  for (const l of ['A', 'B', 'E', 'G', 'K', 'L', 'M', 'N']) assert.ok(new RegExp('^ {2}' + l + '\\. ', 'm').test(md), 'rule ' + l);
});

test('PROTOCOL.md ships with the plugin (Claude and Codex share the root) and is under the plugin size ratchet', () => {
  assert.strictEqual(CORE.PROTOCOL_PATH, path.join(T.PLUGIN, 'PROTOCOL.md'));
  assert.ok(md.length < 40000);
});
