pub const PY: [(&str, &str); 40] = [
    ("fakeOs", "import os\nos.fakefn()\n"),
    ("fakeOsPath", "import os\nprint(os.path.nope_join(\"a\"))\n"),
    ("realOs", "import os\nprint(os.path.join(\"a\", \"b\"))\n"),
    ("fakeAlias", "import os.path as p\np.fake_thing()\n"),
    ("fakeJson", "import json\njson.loads_all(\"x\")\n"),
    ("realJson", "import json\njson.dumps({})\n"),
    ("fakeMath", "import math\nx = math.fake_const\n"),
    ("fromImport", "from os import path\npath.fake_fn()\n"),
    ("fromImportAs", "from collections import OrderedDict as OD\nOD.fake()\n"),
    ("shadowParam", "import os\ndef f(os):\n    return os.fake\n"),
    ("shadowAssign", "import os\nos = 5\nos.fake\n"),
    ("shadowWith", "import io\nwith open(\"a\") as io:\n    io.fake\n"),
    ("inString", "import os\ns = \"os.fakefn()\"\n"),
    ("inComment", "import os\n# os.fakefn()\n"),
    ("inDocstring", "import os\n\"\"\"os.fakefn()\"\"\"\n"),
    ("noImport", "os.fakefn()\n"),
    ("importInString", "s = \"import os\"\nos.fakefn()\n"),
    ("dunder", "import os\nos.__fake__\n"),
    ("local", "import mymod\nmymod.fake()\n"),
    ("relative", "from . import util\nutil.fake()\n"),
    ("third", "import numpy as np\nnp.fake_fn()\n"),
    ("thirdReal", "import numpy as np\nnp.array([1])\n"),
    ("multi", "import os, sys\nsys.fakeattr\nos.fake2\n"),
    ("asyncio", "import asyncio\nasyncio.fake_task()\n"),
    ("typing", "import typing\ntyping.FakeType\n"),
    ("crlf", "import os\r\nos.fakefn()\r\n"),
    ("tabs", "\timport os\n\tos.fakefn()\n"),
    ("unicodeBefore", "import os\n\u{e9}os.fakefn()\n"),
    ("unicodeAfter", "import os\nos\u{e9}.fakefn()\n"),
    ("mixed", "import os\nimport re\nre.fake_fn()\nos.path.join(\"a\")\n"),
    ("empty", ""),
    ("onlyImport", "import os\n"),
    ("big", "" /* built in code */),
    ("classAttr", "import os\nclass A:\n    os = 1\nA.os.fake\n"),
    ("lambdaParam", "import os\nf = lambda os: os.fake\n"),
    ("forVar", "import os\nfor os in range(3):\n    os.fake\n"),
    ("exceptAs", "import os\ntry:\n    pass\nexcept Exception as os:\n    os.fake\n"),
    ("star", "from os import *\nfake()\n"),
    ("semi", "import os; os.fakefn()\n"),
    ("indentedImport", "def f():\n    import os\n    os.fakefn()\n"),
];

pub const JS: [(&str, &str); 47] = [
    ("reqFs", "const fs = require('fs');\nfs.fakeFn('a');\n"),
    ("reqFsReal", "const fs = require('fs');\nfs.readFileSync('a');\n"),
    ("reqInline", "require('path').nonsense('a');\n"),
    ("reqInlineReal", "require('path').join('a');\n"),
    ("reqPathSpec", "const x = require('./x');\nx.fake();\n"),
    ("reqAbs", "require('/abs/mod').fake;\n"),
    ("reqDotDot", "require('a/../b').fake;\n"),
    ("reqBackslash", "require('a\\\\b').fake;\n"),
    ("reqScoped", "const q = require('@scope/pkg');\nq.fake();\n"),
    ("thirdLodash", "const _ = require('lodash');\n_.fakeFn();\n"),
    ("gArray", "Array.fakeStatic(1);\n"),
    ("gArrayReal", "Array.isArray(1);\n"),
    ("gProto", "Array.prototype.fakeProto.call(1);\n"),
    ("gProtoReal", "Array.prototype.map.call([], x => x);\n"),
    ("gObject", "Object.nope({});\n"),
    ("gJson", "JSON.parse_all(\"x\");\n"),
    ("gJsonReal", "JSON.stringify({});\n"),
    ("gMath", "Math.fakeMath(1);\n"),
    ("gPromise", "Promise.fakeAll([]);\n"),
    ("gDate", "Date.fakeNow();\n"),
    ("gBuffer", "Buffer.fakeFrom(\"a\");\n"),
    ("gSymbol", "Symbol.fakeIterator;\n"),
    ("gReflect", "Reflect.fake({});\n"),
    ("shadowParam", "function f(Array) { return Array.fake(); }\n"),
    ("shadowConst", "const Math = {};\nMath.fake();\n"),
    ("shadowAssign", "Object = {};\nObject.fake();\n"),
    ("inString", "const s = 'Array.fakeStatic';\n"),
    ("inComment", "// Array.fakeStatic\n/* Math.fake */\n"),
    ("inTemplate", "const s = `Array.fakeStatic`;\n"),
    ("reqInComment", "// const fs = require('fs'); fs.fake\n"),
    ("assignProp", "const fs = require('fs');\nfs.fake = 1;\n"),
    ("reassign", "let fs = require('fs');\nfs = other;\nfs.fake;\n"),
    ("tsImport", "import fs from 'fs';\nfs.fakeFn();\n"),
    ("tsType", "const a: Array<string> = [];\nArray.fakeStatic;\n"),
    ("nodeColon", "const fs = require('node:fs');\nfs.fake;\n"),
    ("dunder", "const fs = require('fs');\nfs.__fake;\n"),
    ("multi", "const fs = require('fs'), p = require('path');\np.fake;\n"),
    ("unicode", "Array.fake\u{e9}();\n"),
    ("unicodeBefore", "\u{e9}Array.fake();\n"),
    ("crlf", "const fs = require('fs');\r\nfs.fakeFn();\r\n"),
    ("empty", ""),
    ("plain", "const a = 1;\nconsole.log(a);\n"),
    ("big", "" /* built in code */),
    ("regexLit", "const r = /Array.fake/;\n"),
    ("methodChain", "foo.Array.fake();\n"),
    ("optional", "Array?.fake();\n"),
    ("mathPI", "Math.PI;\nMath.fakeX;\n"),
];

pub const PYEXT: [&str; 10] = [
    "x.py",
    "x.pyi",
    "X.PY",
    "dir/a.b.py",
    "a.py.txt",
    "a.pyc",
    "py",
    ".py",
    "a.pyw",
    "a.pyx",
];

pub const JSEXT: [&str; 14] = [
    "x.js",
    "x.mjs",
    "x.cjs",
    "x.ts",
    "x.tsx",
    "x.jsx",
    "X.JS",
    "a.js.map",
    "a.json",
    "a.jsx.bak",
    "a.d.ts",
    "a.mts",
    "a.cts",
    "js",
];

pub const OTHER: [&str; 8] = [
    "README.md",
    "a.rs",
    "a.sh",
    "Makefile",
    "a",
    "",
    "a.PY ",
    "a.py\n",
];

pub const SH: [&str; 94] = [
    "cat > a.py <<'EOF'\nimport os\nos.fakefn()\nEOF",
    "cat > a.py <<EOF\nimport os\nos.fakefn()\nEOF",
    "cat >> a.py <<'EOF'\nimport os\nos.fakefn()\nEOF",
    "cat <<'EOF' > a.py\nimport os\nos.fakefn()\nEOF",
    "cat <<'EOF' | tee a.py\nimport os\nos.fakefn()\nEOF",
    "tee a.py <<EOF\nimport os\nos.fakefn()\nEOF",
    "cat > dir/a.js <<'EOF'\nArray.fakeStatic(1);\nEOF",
    "cat > a.ts <<'EOF'\nconst fs = require('fs');\nfs.fakeFn();\nEOF",
    "echo \"import os\\nos.fakefn()\\n\" > a.py",
    "echo -e \"import os\\nos.fakefn()\\n\" > a.py",
    "printf \"import os\\nos.fakefn()\\n\" > a.py",
    "printf 'import os\\nos.fakefn()\\n' >> a.py",
    "echo 'Array.fakeStatic(1);\\n' > a.js",
    "echo \"import os; os.fakefn()\" > a.py",
    "echo 'import os; os.fakefn()' | tee a.py",
    "echo 'import os; os.fakefn()' | tee -a a.py b.py",
    "printf 'import json\\njson.nope\\n' | tee b.py",
    "sed -i 's/x/os.fakefn()/' a.py",
    "sed -i '' 's/x/os.fakefn()/' a.py",
    "perl -pi -e 's/x/os.fakefn()/' a.py",
    "cp a.py b.py",
    "mv a.py b.py",
    "python3 -c \"open('a.py','w').write('import os\\nos.fakefn()')\"",
    "python -c 'open(\"a.py\", \"a\").write(\"import os; os.fake\")'",
    "python3 - <<'PY'\nopen('a.py','w').write('import os\\nos.fakefn()')\nPY",
    "node -e \"require('fs').writeFileSync('a.js','Array.fakeStatic()')\"",
    "bash -c 'cat > a.py <<EOF\nimport os\nos.fake()\nEOF'",
    "sh -c \"echo 'import os; os.fake' > a.py\"",
    "f=a; echo \"import os; os.fake\" > $f.py",
    "echo \"import os; os.fake\" > \"a b.py\"",
    "echo 'import os; os.fake' > 'a b.py'",
    "echo \"import os; os.fake\" > ./sub/../a.py",
    "echo \"import os; os.fake\" > /tmp/a.py",
    "echo \"import os; os.fake\" > ~/a.py",
    "echo \"import os; os.fake\" > a.PY",
    "echo \"import os; os.fake\" > a.py && echo done",
    "cd src && cat > a.py <<EOF\nimport os\nos.fake()\nEOF",
    "ls a.py",
    "cat a.py",
    "grep fake a.py",
    "python3 a.py",
    "node a.js",
    "git add a.py",
    "git commit -m \"add a.py\"",
    "rm a.py",
    "echo hi > out.txt",
    "echo \"import os; os.fake\" > out.txt",
    "cat > a.sh <<EOF\nimport os\nos.fake\nEOF",
    "cat > a.py <<'EOF'\nimport os\nos.path.join('a')\nEOF",
    "cat > a.js <<'EOF'\nconst a = 1;\nEOF",
    "npm test -- a.test.js",
    "pytest tests/test_a.py",
    "eslint src/a.ts src/b.tsx",
    "tsc --noEmit a.ts",
    "python3 -m py_compile a.py",
    "echo x > a.pyi",
    "echo x > a.mjs",
    "echo x > a.cjs",
    "echo x > a.jsx",
    "echo x > a.tsx",
    "echo x > a.pyc",
    "echo x > a.json",
    "curl -o a.js https://x/y.js",
    "wget -O a.py https://x/y.py",
    "unzip a.zip",
    "echo \".py\"",
    "echo py",
    "a.py",
    "",
    "   ",
    "cat > a.py <<EOF\nimport os\nos.fake\n",
    "cat <<EOF > a.py\nimport os\r\nos.fake()\r\nEOF",
    "echo $'import os\\nos.fake()' > a.py",
    "echo \"import os\u{a0}os.fake()\" > a.py",
    "echo \"\u{e9}.py\"",
    "echo x > \u{e9}.py",
    "echo x > a.py",
    "x=.py; echo \"import os; os.fake\" > a$x",
    "echo \"imp\"\"ort os; os.fake\" > a.py",
    "echo 'Arr''ay.fakeStatic(1);' > a.js",
    "echo 'i\\mport os; os.fake' > a.py",
    "printf '%s\\n%s\\n' 'import os' 'os.fake' > a.py",
    "printf '%2$s\\n%1$s\\n' 'os.fake' 'import os' > a.py",
    "cat > a.py <<'EOF'\nfrom os import fakefn\nEOF",
    "cat > a.ts <<'EOF'\nconst c = require('crypto');\nc.nope();\nEOF",
    "echo \"x = 1\" > a.py",
    "echo \"x = 1\" > a.js 2>&1",
    "grep -n foo a.py > out.txt",
    "ls a.py 2>/dev/null",
    "sed -n 1,5p a.py | head",
    "cat a.py | grep import > out.txt",
    "echo 'const o = 1;' | tee a.ts",
    "cat > a.py <<'EOF'\nimport collections\nx = collections.OrderedDict()\nEOF",
    "echo \"import numpy\" > a.py; numpy.fake",
];

pub const PATCHES: [&str; 19] = [
    "*** Begin Patch\n*** Add File: a.py\n+import os\n+os.fakefn()\n*** End Patch",
    "*** Begin Patch\n*** Add File: a.js\n+Array.fakeStatic(1);\n*** End Patch",
    "*** Begin Patch\n*** Update File: a.py\n@@\n import os\n+os.fakefn()\n*** End Patch",
    "*** Begin Patch\n*** Update File: a.py\n*** Move to: b.js\n@@\n+Array.fakeStatic(1);\n*** End Patch",
    "*** Begin Patch\n*** Update File: a.txt\n*** Move to: b.py\n@@\n+import os\n+os.fakefn()\n*** End Patch",
    "*** Begin Patch\n*** Delete File: a.py\n*** End Patch",
    "*** Begin Patch\n*** Add File: a.md\n+import os\n+os.fakefn()\n*** End Patch",
    "*** Begin Patch\n*** Add File: a.py\n+import os\n+os.path.join(\"a\")\n*** End Patch",
    "*** Begin Patch\n*** Add File: a.ts\n+const fs = require(\"fs\");\n+fs.fakeFn();\n*** End Patch",
    "*** Begin Patch\n*** Add File: a.py\n+x = 1\n*** Add File: b.js\n+Array.fakeStatic(1);\n*** End Patch",
    "*** Begin Patch\n*** Add File: a.py\n+import os\n+os.fake()\n",
    "not a patch",
    "",
    "*** Begin Patch\n\n*** End Patch",
    "*** Begin Patch\n*** Add File: a.py\n*** End Patch",
    "*** Begin Patch\n*** Add File: dir/sub/a.py\n+import json\n+json.nope\n*** End Patch",
    "*** Begin Patch\n*** Add File: a.PY\n+import os\n+os.fake()\n*** End Patch",
    "*** Begin Patch\n*** Add File: a b.py\n+import os\n+os.fake()\n*** End Patch",
    "*** Begin Patch\n*** Update File: a.py\n@@ def f():\n-    os.x\n+    os.fakefn()\n*** End Patch",
];
