pub(crate) const WORK: [&str; 21] = [
    "git commit -m x",
    "git commit -am msg",
    "git push",
    "git push origin dev",
    "git add -A && git commit -m y",
    "git rebase main",
    "git merge other",
    "git cherry-pick abc",
    "git reset --hard HEAD~1",
    "git restore f",
    "git rm f",
    "git mv a b",
    "git pull",
    "git revert HEAD",
    "git am x.patch",
    "gh pr create --title x --body y",
    "gh pr merge 1",
    "gh issue create --title x",
    "gh release create v1",
    "git tag v1",
    "git tag -d v1",
];

pub(crate) const RECOVERY: [&str; 7] = [
    "git rebase --abort",
    "git merge --abort",
    "git cherry-pick --abort",
    "git am --abort",
    "git revert --quit",
    "git stash pop",
    "git stash apply",
];

pub(crate) const READ: [&str; 24] = [
    "ls",
    "ls -la",
    "git status",
    "git log --oneline",
    "git diff",
    "git show HEAD",
    "cat README.md | head -20",
    "pwd",
    "grep -r foo src",
    "rg foo",
    "wc -l f",
    "git log --oneline | wc -l",
    "which node",
    "whoami",
    "stat f",
    "du -sh .",
    "git rev-parse HEAD",
    "git ls-files",
    "git blame f",
    "git describe",
    "true",
    "false",
    "ls && pwd; git status",
    "ls\ngit status",
];

pub(crate) const OTHER: [&str; 29] = [
    "npm test",
    "node script.js",
    "echo hi",
    "cd /tmp",
    "make build",
    "python3 x.py",
    "curl -s http://localhost",
    "cat <<EOF\nx\nEOF",
    "ls $(pwd)",
    "echo \"a b\" | wc -c",
    "find . -name x",
    "sleep 1",
    "git diff --output=x",
    "git log -o x",
    "ls > out.txt",
    "FOO=1 ls",
    "ls *.js",
    "bash -c \"git commit -m x\"",
    "echo x > /tmp/ah-notes.md",
    "sed -i s/a/b/ f",
    "rm -rf build",
    "mkdir -p x",
    "touch f",
    "cp a b",
    "tee f < in",
    "git status && git commit -m z",
    "ls || git push",
    "  ",
    "",
];

pub(crate) const FRAG: [&str; 36] = [
    "ls",
    "git",
    "status",
    "commit",
    "-m",
    "x",
    "push",
    "cat",
    "f",
    "head",
    "|",
    "$(",
    ")",
    "\"",
    "'",
    ">",
    "<",
    "*",
    "{",
    "}",
    "\\",
    "FOO=1",
    "log",
    "--output",
    "-o",
    "diff",
    "wc",
    "grep",
    "a.b",
    "/",
    "-",
    "=",
    "@",
    "%",
    "+",
    ",",
];

pub(crate) const WS: [&str; 9] = [
    " ",
    "\t",
    "\n",
    ";",
    "&&",
    "||",
    "|",
    "&",
    " \\\n",
];
