pub(crate) const PRED: [&str; 55] = [
    "grep -q foo file",
    "grep foo file",
    "rg pattern src",
    "test -f /nonexistent",
    "[ -d /x ]",
    "[[ -z \"$X\" ]]",
    "diff a b",
    "cmp a b",
    "pgrep node",
    "which nosuchtool",
    "type foo",
    "git diff --quiet",
    "git diff --exit-code HEAD",
    "git -C /repo diff --quiet",
    "git merge-base --is-ancestor a b",
    "git grep foo",
    "git cat-file -e HEAD:x",
    "git ls-files --error-unmatch f",
    "git show-ref --verify refs/heads/x",
    "git show-ref -q x",
    "command -v node",
    "command -V node",
    "FOO=1 command -v x",
    "cat f | grep x",
    "ls | grep -q x",
    "echo hi && grep x f",
    "true && test -f x",
    "echo a; grep x f",
    "make\ngrep x f",
    "cd /tmp && grep x f",
    "env grep x f",
    "time grep x f",
    "nice -n 5 grep x f",
    "nohup grep x f",
    "FOO=bar grep x f",
    "/usr/bin/grep x f",
    "builtin test -f x",
    "ack foo",
    "ag foo",
    "ugrep foo",
    "egrep a f",
    "fgrep a f",
    ": && grep a f",
    "printf x && grep a f",
    "grep a f 2>/dev/null",
    "grep a f > /dev/null 2>&1",
    "cat <<< x | grep a",
    "ls |& grep a",
    "a \\\n| grep x",
    "grep a f # comment",
    "echo \"a;b\" ; grep x f",
    "echo 'a && b' && grep x f",
    "grep \"a|b\" f",
    "X=$(echo y) grep a f",
    "grep a $(echo f)",
];

pub(crate) const NOTPRED: [&str; 48] = [
    "npm test",
    "make build",
    "ls /nonexistent",
    "cat nofile",
    "git status",
    "git diff",
    "git push",
    "grep a f || echo no",
    "if grep a f; then echo y; fi",
    "for i in 1 2; do grep a f; done",
    "set -e; grep a f",
    "grep a f; exit 1",
    "bash -e -c \"grep a f\"",
    "sh -ec \"grep a f\"",
    "grep a f &",
    "grep a f & ",
    "set -o pipefail; grep a f",
    "cat <<EOF\nx\nEOF",
    "grep a f && echo done",
    "grep a f && npm test",
    "echo $(grep a f)",
    "grep a f | tee out",
    "grep a f | wc -l",
    "(grep a f)",
    "{ grep a f; }",
    "! grep a f",
    "eval \"grep a f\"",
    "trap x EXIT; grep a f",
    "exec grep a f",
    "while true; do grep a f; done",
    "case x in x) grep a f;; esac",
    "function f { grep a f; }",
    "# only a comment",
    "",
    "   ",
    "grep a f \\",
    "echo 'unbalanced",
    "echo \"unbalanced",
    "echo `unbalanced",
    "grep a `echo f`",
    "tail -f x | grep a",
    "test -f x || true",
    "grep a f ; ",
    "grep a f ;; ",
    "echo x &&",
    "curl -f http://x",
    "node script.js",
    "python3 -c \"import sys; sys.exit(1)\"",
];

pub(crate) const FRAG: [&str; 37] = [
    "grep",
    "test",
    "[",
    "diff",
    "echo",
    "true",
    ":",
    "git",
    "diff",
    "--quiet",
    "-q",
    "x",
    "f",
    "command",
    "-v",
    "node",
    "$(",
    ")",
    "`",
    "\"",
    "'",
    "{",
    "}",
    "(",
    "if",
    "then",
    "fi",
    "2>&1",
    ">",
    "<",
    "<<",
    "set",
    "-e",
    "exec",
    "FOO=1",
    "!",
    "#",
];

pub(crate) const WS: [&str; 11] = [
    " ",
    "\t",
    "\n",
    ";",
    "&&",
    "||",
    "|",
    "|&",
    "&",
    "\\\n",
    "  ",
];

pub(crate) const ERR: [Option<&str>; 20] = [
    Some("Exit code 1\n"),
    Some("Exit code 1"),
    Some("Exit code 2\n"),
    Some("Exit code 01\n"),
    Some("Exit code 0\n"),
    Some("Exit code 10\n"),
    Some("exit code 1"),
    Some("  Exit code 1\nstuff"),
    Some("Exit code 1abc"),
    Some("Exit code 1_"),
    Some("Exit code 1.5"),
    Some("Exit code 100000000000000000001"),
    Some(""),
    Some("Error: something"),
    None,
    Some("This agent is isolated in the worktree /x"),
    Some("This session is isolated in the worktree\nmore"),
    Some("  This agent is isolated in the worktree"),
    Some("This agent is isolated in the worktrees"),
    Some("This workspace is isolated in the worktree"),
];
