pub(crate) const HAND: [&str; 100] = [
    "git commit -am x",
    "git push origin dev",
    "git status",
    "git log --oneline",
    "git checkout -b x",
    "git stash",
    "git reset --hard",
    "git apply p.diff",
    "git am p.mbox",
    "git clean -fd",
    "git switch main",
    "git restore a",
    "git rebase main",
    "git merge x",
    "git cherry-pick abc",
    "sed -i s/a/b/ f",
    "sed -n 1p f",
    "npm install",
    "npm i x",
    "npm ci",
    "npm test",
    "pnpm add x",
    "yarn install",
    "yarn dev",
    "pip install x",
    "pip list",
    "patch -p1 < x.patch",
    "patched",
    "rm f",
    "cp a b",
    "mv a b",
    "tee f",
    "mkdir d",
    "touch f",
    "make",
    "chmod +x f",
    "ls",
    "cat f",
    "echo hi",
    "echo hi > f",
    "echo hi >> f",
    "echo hi 2>/dev/null",
    "cmd 2>&1",
    "cmd >&2",
    "cmd &> f",
    "cmd > /dev/null",
    "cmd >| f",
    "a && rm b",
    "a; rm b",
    "a | tee f",
    "(rm f)",
    "echo $(rm f)",
    "echo `rm f`",
    "echo \"rm f\"",
    "echo 'git commit'",
    "echo \"a > b\"",
    "grep x f > out",
    "rm /tmp/x",
    "rm -rf /private/tmp/claude-501/x/scratchpad/y",
    "cat > /x/scratchpad/y <<EOF\nz\nEOF",
    "cat > .anti-hall/progress/x.md <<EOF\nz\nEOF",
    "echo x >> .anti-hall/history/2026/x.md",
    "echo x >> .anti-hall/handovers/a/b.md",
    "git commit -m x && rm /x/scratchpad/y",
    "cp /x/scratchpad/a /repo/b",
    "cp /x/scratchpad/a /x/scratchpad/b",
    "node devswarm.js inbox read-primary abc",
    "node /a/b/devswarm.js heartbeat",
    "devswarm.js send abc msg",
    "node devswarm.js inbox pull && npm test",
    "node devswarm.js roster > src/x.js",
    "crontab -l",
    "crontab -l > /tmp/x",
    "crontab -l > src/x",
    "crontab-parser x",
    "(crontab -l; echo x) | crontab -",
    "node devswarm.js send x <<EOF\na -> b\nEOF",
    "node devswarm.js send x <<EOF\n$(rm f)\nEOF",
    "node devswarm.js nudge x # <<EOF",
    "cat <<EOF > f\nx\nEOF",
    "cat <<-EOF\nx\nEOF",
    "echo a<<<b",
    "git commit\r\n",
    "echo a\rrm b",
    "echo a\u{2028}rm b",
    "x\nrm f",
    "RM f",
    "Git Commit",
    "sed -I x",
    "sed --in-place x",
    "",
    " ",
    "rm",
    "m",
    "git",
    "make -j4",
    "echo \"unclosed rm f",
    "echo 'unclosed rm f",
    "a \\\" b; rm f",
    "echo \"a\\\"b\" > f",
];

pub(crate) const WORDS: [&str; 51] = [
    "git commit",
    "git push",
    "rm",
    "cp",
    "mv",
    "tee",
    "mkdir",
    "touch",
    "make",
    "chmod",
    "sed -i",
    "npm install",
    "pip install",
    "patch",
    "git checkout",
    ">",
    ">>",
    "2>",
    "&>",
    ">&2",
    "\"",
    "'",
    "\\",
    ";",
    "&&",
    "||",
    "|",
    "&",
    "(",
    ")",
    "`",
    "$(",
    "\n",
    "\r",
    " ",
    "  ",
    "/scratchpad/",
    "/tmp/",
    ".anti-hall/progress/",
    ".anti-hall/history/",
    "x",
    "file.txt",
    "<<EOF",
    "EOF",
    "#",
    "devswarm.js",
    "inbox read",
    "crontab",
    "-l",
    "-i",
    "\u{1f600}",
];
