pub(crate) const VERBS: [&str; 44] = [
    "git commit -m x",
    "git commit --amend --no-edit",
    "git cherry-pick abc",
    "git revert HEAD",
    "git merge other",
    "git rebase main",
    "git rebase -i HEAD~3",
    "git pull",
    "git am x.patch",
    "git commit -am msg",
    "git tag -a v1 -m x",
    "git stash",
    "git push",
    "git status",
    "git log",
    "git diff",
    "git add .",
    "git checkout x",
    "git switch x",
    "git reset --hard",
    "git fetch",
    "git ci -m x",
    "git cm x",
    "git sh",
    "git st",
    "git chain",
    "git loop",
    "git opt",
    "git rb",
    "git unknownsub",
    "git",
    "git -C /nonexistent commit -m x",
    "GIT_DIR=x git commit",
    "FOO=1 git commit -m x",
    "sudo git commit -m x",
    "env git commit -m x",
    "command git commit -m x",
    "time git commit -m x",
    "nice git commit -m x",
    "xargs git commit",
    "echo git commit",
    "echo \"git commit\"",
    "ls",
    "true",
];

pub(crate) const CDLIST: [&str; 44] = [
    "cd $HOME/mixed && git commit -m x",
    "cd mixed && git commit -m x",
    "cd .. && cd mixed && git commit -m x",
    "cd /nonexistent && git commit -m x",
    "cd -- && git commit",
    "cd -P $HOME/mixed && git commit",
    "cd && git commit",
    "cd ~ && git commit",
    "cd \"$HOME/mixed\" && git commit",
    "cd '$HOME/sp ace' && git commit",
    "cd $HOME/sp\\ ace && git commit",
    "git -C $HOME/mixed commit -m x",
    "git -C mixed commit -m x",
    "git -C ../mixed commit -m x",
    "git -C $HOME/mixed -c user.name=x commit",
    "git -c user.name=x -C $HOME/mixed commit",
    "git --git-dir=$HOME/mixed/.git commit",
    "git --git-dir $HOME/mixed/.git commit",
    "git --work-tree=$HOME/mixed commit",
    "git --namespace x commit",
    "git --no-pager -C $HOME/mixed commit",
    "git -C $HOME/mixed -C $HOME/clean commit",
    "git -C $HOME/mixed -C ../clean commit",
    "git -C . commit",
    "git -C ./sub\\ dir commit",
    "git -C \"sub dir\" commit",
    "cd $HOME/mixed && git commit -m x; cd $HOME/clean && git commit -m y",
    "cd $HOME/mixed; git commit; cd $HOME/recent; git commit",
    "cd $HOME/mixed && git commit && cd $HOME/mixed && git commit",
    "git -C $HOME/mixed commit; git -C $HOME/mixed commit",
    "git -C $HOME/mixed commit; git -C $HOME/recent commit; git -C $HOME/old commit",
    "git -C $HOME/clean commit; git -C $HOME/old commit",
    "(cd $HOME/mixed && git commit)",
    "bash -c \"cd $HOME/mixed && git commit\"",
    "cd $HOME/mixed\ngit commit",
    "cd $HOME/mixed && bash -c \"git commit\"",
    "pushd $HOME/mixed && git commit",
    "cd $HOME/mixed || git commit",
    "cd $HOME/aliased && git ci",
    "cd $HOME/aliased && git cm x",
    "cd $HOME/aliased && git sh",
    "cd $HOME/aliased && git chain",
    "git -C $HOME/aliased ci -m x",
    "git -C $HOME/aliased st",
];

pub(crate) const WS: [&str; 9] = [
    " ",
    "\t",
    "\n",
    ";",
    "&&",
    "||",
    "|",
    "&",
    " \\\n",
];

pub(crate) const FRAG: [&str; 28] = [
    "git",
    "commit",
    "-m",
    "x",
    "-C",
    "$HOME/mixed",
    "$HOME/recent",
    "cd",
    "eval",
    "bash",
    "-c",
    "\"git commit\"",
    "'git commit'",
    "$(",
    ")",
    "`",
    "(",
    ")",
    "-c",
    "user.name=x",
    "--amend",
    "ci",
    "sh",
    "sudo",
    "env",
    "FOO=1",
    "--git-dir",
    "$HOME/mixed/.git",
];
