//! Collects the settings keys this build reads, so a plugin whose defaults lack one is rejected when the engine loads
//! them (a plugin and an engine of different versions) instead of panicking later in a hook call.
//!
//! This is the ONLY thing the build derives from the source about configuration, and it is a schema, not configuration:
//! no value, table, message or default is compiled in (the defaults are read from the plugin's files at run time, D17).
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

const CALLERS: [&str; 9] = ["num", "millis", "secs", "text", "list", "words", "render", "raw", "env_of"];

fn rust_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(rd) = std::fs::read_dir(dir) else { return };
    for e in rd.flatten() {
        let p = e.path();
        if p.is_dir() {
            rust_files(&p, out);
        } else if p.extension().is_some_and(|x| x == "rs") && p.file_name().is_some_and(|n| n != "tests.rs") {
            out.push(p);
        }
    }
}

fn main() {
    let src = Path::new(&std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|e| panic!("CARGO_MANIFEST_DIR: {e}"))).join("src");
    println!("cargo:rerun-if-changed={}", src.display());
    let mut files = Vec::new();
    rust_files(&src, &mut files);
    let mut keys = BTreeSet::new();
    for f in &files {
        let text = std::fs::read_to_string(f).unwrap_or_else(|e| panic!("{}: {e}", f.display()));
        // test modules may name keys on purpose, including in negative tests
        let text = text.split("#[cfg(test)]\nmod tests {").next().unwrap_or("");
        for c in CALLERS {
            let needle = format!("defaults::{c}(\"");
            let mut rest = text;
            while let Some(p) = rest.find(&needle) {
                let after = &rest[p + needle.len()..];
                if let Some(end) = after.find('"') {
                    let k = &after[..end];
                    if k.contains('.') && k.chars().all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '_' || ch == '.') {
                        keys.insert(k.to_string());
                    }
                }
                rest = after;
            }
        }
    }
    let mut code = String::from(
        "// @generated by build.rs from the source; do not edit.\n/// The settings keys the source reads, sorted.\npub static REQUIRED: &[&str] = &[\n",
    );
    for k in &keys {
        code.push_str(&format!("    {k:?},\n"));
    }
    code.push_str("];\n");
    let out = Path::new(&std::env::var("OUT_DIR").unwrap_or_else(|e| panic!("OUT_DIR: {e}"))).join("required_keys.rs");
    std::fs::write(&out, code).unwrap_or_else(|e| panic!("write {}: {e}", out.display()));
}
