//! Collects the settings keys this build reads, so a plugin whose defaults lack one is rejected when the engine loads
//! them (a plugin and an engine of different versions) instead of panicking later in a hook call.
//!
//! This is the ONLY thing the build derives from the source about configuration, and it is a schema, not configuration:
//! no value, table, message or default is compiled in (the defaults are read from the plugin's files at run time, D17).
#[path = "build_support/keyscan.rs"]
mod keyscan;
use std::path::Path;

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|e| panic!("CARGO_MANIFEST_DIR: {e}"));
    let src = Path::new(&manifest).join("src");
    println!("cargo:rerun-if-changed={}", src.display());
    println!("cargo:rerun-if-changed={}", Path::new(&manifest).join("build_support").display());
    let keys = keyscan::scan(&src);
    let mut code = String::from(
        "// @generated by build.rs from the source; do not edit.\n/// The settings keys the source reads, sorted, with the type each read expects.\npub static REQUIRED: &[(&str, super::Kind)] = &[\n",
    );
    for (k, kind) in &keys {
        code.push_str(&format!("    ({k:?}, super::Kind::{}),\n", kind.name()));
    }
    code.push_str("];\n");
    let out = Path::new(&std::env::var("OUT_DIR").unwrap_or_else(|e| panic!("OUT_DIR: {e}"))).join("required_keys.rs");
    std::fs::write(&out, code).unwrap_or_else(|e| panic!("write {}: {e}", out.display()));
}
